name: "Break the build SAST + SCA"
on:
  workflow_dispatch

jobs:
  build:
    runs-on: Ubuntu-latest
    env:
      POLARIS_SERVER_URL:  ${{ secrets.POLARIS_SERVER_URL }}
      POLARIS_ACCESS_TOKEN:  ${{ secrets.POLARIS_ACCESS_TOKEN }}
      BLACKDUCK_URL: ${{ secrets.BLACKDUCK_URL}}
      BLACKDUCK_API_TOKEN: ${{ secrets.BLACKDUCK_API_TOKEN }}

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    # Perform Polaris Analysis
    - name: Coverity on Polaris
      run: |
        curl -fLOsS $POLARIS_SERVER_URL/api/tools/polaris_cli-linux64.zip
        unzip -d /tmp -jo polaris_cli-linux64.zip
        /tmp/polaris analyze -w
  #     if [ $(cat .synopsys/polaris/cli-scan.json | jq .issueSummary.issuesBySeverity.high) -ne 0 ]; then exit 1; elif [ $(cat .synopsys/polaris/cli-scan.json | jq .issueSummary.issuesBySeverity.medium) -ne 0 ]; then exit 0; exit 0; fi  
        
    # Perform Software Composition Analysis - Failing the build on BLOCKER POLICIES        
    - name: Black Duck (SCA)
      run: |
          mvn package
          bash <(curl -s -L https://detect.synopsys.com/detect7.sh) '--blackduck.url=$BLACKDUCK_URL \
             --blackduck.api.token=$BLACKDUCK_API_TOKEN \
             --detect.project.name=sig-demo/insecure-bank \
             --detect.project.version.name=main \
             --detect.code.location.name=insecure-bank-main \
             --detect.policy.check.fail.on.severities=BLOCKER'
