name: Black Duck - Rapid Scan

on:
  workflow_dispatch

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    env:
      BLACKDUCK_URL: ${{ secrets.BLACKDUCK_URL}}
      BLACKDUCK_API_TOKEN: ${{ secrets.BLACKDUCK_API_TOKEN }}
      
    steps:
      - name: check out code
        uses: actions/checkout@v2
        
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
        
     # Perform Software Composition Analysis - Rapid scan             
      - name: Black Duck (SCA)
        run: |
          bash <(curl -s -L https://detect.synopsys.com/detect7.sh) '--blackduck.url=$BLACKDUCK_URL \
             --blackduck.api.token=$BLACKDUCK_API_TOKEN \
             --detect.project.name=sig-demo/insecure-bank \
             --detect.project.version.name=main \
             --detect.blackduck.scan.mode=RAPID' 
